### ISSUE TITLE
`null` is passed as credentials when clicking on the link on the homepage

### ISSUE THREAD

**Issue by slavaboiko** [maxisme/notifi#122]
when you click on the "HTTP Requests" link on the homepage, it takes you to the website to make a test HTTP call, but `credentials` are not populated and coming as `null`.

when clicking on the "How do I receive notifications" in the menu - everything works fine!

**Comment by maxisme** [comment]
Need to check `$credentials != null` - https://github.com/maxisme/notifi/blob/master/lib/notifications/notifications_table.dart#L102
