### ISSUE TITLE
Application crashes on startup

### ISSUE THREAD

**Issue by onderweg** [maxisme/notifi#3]
Hello,

Unfortunately, the application crashes before UI is visible; MacOS 10.12.3.

Extract from MacOS crash report:

```
Process:               notifi [30465]
Path:                  /Applications/notifi.app/Contents/MacOS/notifi

Crashed Thread:        0

Exception Type:        EXC_CRASH (Code Signature Invalid)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace CODESIGNING, Code 0x1`
```

**Comment by maxisme** [comment]
Sorry about that. Is that when downloading from https://notifi.it/download ?

**Comment by onderweg** [comment]
Yes, indeed

**Comment by maxisme** [comment]
Strange! Trying to automate a lot of the tedious work needed to deploy this app so must be a problem there. Will fix by 5:30pm! Currently sat on the beach as there is finally good weather in the U.K :)

**Comment by maxisme** [comment]
Working on it now. I have had this problem before. It is super annoying.

**Comment by maxisme** [comment]
Fixed. Was an issue with a developed deploy script I wrote. Thank you for reporting.

**Comment by onderweg** [comment]
Thanks for the quick fix!

**Comment by onderweg** [comment]
There seems to be a new issue now. Application starts, but an error message in popup appears:

```
Error Fetch credentials!

Error message: Error Domain=NSURLErrorDomain Code=-1002 "unsupported URL" UserInfo={NSUnderlyingError=0x60800005d760 {Error Domain=kCFErrorDomainCFNetwork Code=-1002 "unsupported URL" UserInfo={NSErrorFailingURLStringKey=, NSLocalizedDescription=unsupported URL, NSErrorFailingURLKey=}}, NSErrorFailingURLStringKey=, NSErrorFailingURLKey=, NSLocalizedDescription=unsupported URL
```

**Comment by maxisme** [comment]
Really sorry about that. Please update the app by clicking the: Settings icon > Check For Updates... Thank you so much for reporting these issues.
